[build]
  command = "npx @11ty/eleventy"
  publish = "_site"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "24"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200